"""establish learning platform legacy baseline

Revision ID: lp_0001_legacy_baseline
Revises:
Create Date: 2026-07-22 06:22:18.580216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'lp_0001_legacy_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 扩展属于数据库级前置能力；downgrade 不删除共享扩展。
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.create_table('achievements',
    sa.Column('code', sa.String(length=50), nullable=False, comment='成就编码 (FIRST_LEARN / STREAK_7 / ...)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='成就名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='达成条件描述'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='徽章图标'),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='达成条件配置'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('age_groups',
    sa.Column('code', sa.String(length=10), nullable=False, comment='分级编码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='显示名称'),
    sa.Column('min_age', sa.Integer(), nullable=False, comment='最小年龄'),
    sa.Column('max_age', sa.Integer(), nullable=False, comment='最大年龄'),
    sa.Column('theme_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='主题配置（颜色/字号/间距等）'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('courses',
    sa.Column('title', sa.String(length=200), nullable=False, comment='课程标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='课程描述'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科'),
    sa.Column('age_group', sa.String(length=50), nullable=False, comment='年龄段'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='难度: beginner/intermediate/advanced'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='课程总时长(分钟)'),
    sa.Column('rating', sa.Float(), nullable=False, comment='评分'),
    sa.Column('enroll_count', sa.Integer(), nullable=False, comment='报名人数'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='封面图URL'),
    sa.Column('total_lessons', sa.Integer(), nullable=False, comment='总课时数'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('slug', sa.String(length=100), nullable=True, comment='URL标识'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_active', 'courses', ['is_active'], unique=False)
    op.create_index(op.f('ix_courses_age_group'), 'courses', ['age_group'], unique=False)
    op.create_index(op.f('ix_courses_difficulty'), 'courses', ['difficulty'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_index('ix_courses_subject_difficulty', 'courses', ['subject', 'difficulty'], unique=False)
    op.create_table('daily_challenges',
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_challenges_challenge_date'), 'daily_challenges', ['challenge_date'], unique=True)
    op.create_table('evolution_records',
    sa.Column('evolution_type', sa.String(length=50), nullable=False, comment='进化类型: skill_created / skill_updated / memory_cleaned / strategy_changed'),
    sa.Column('trigger_reason', sa.Text(), nullable=False, comment='触发原因'),
    sa.Column('target_name', sa.String(length=200), nullable=False, comment='目标名称'),
    sa.Column('change_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='变更内容'),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更前快照'),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='变更后快照'),
    sa.Column('quality_before', sa.Float(), nullable=True, comment='变更前质量分'),
    sa.Column('quality_after', sa.Float(), nullable=True, comment='变更后质量分'),
    sa.Column('rolled_back', sa.Boolean(), server_default='false', nullable=True, comment='是否已回滚'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evo_created', 'evolution_records', ['created_at'], unique=False)
    op.create_index('idx_evo_target', 'evolution_records', ['target_name'], unique=False)
    op.create_index('idx_evo_type', 'evolution_records', ['evolution_type'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Skill 名称'),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='触发条件（学科、主题、年龄、难度等）'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=True, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='Skill 内容（Markdown）'),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=True, comment='使用成功次数'),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=True, comment='使用失败次数'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('quality_score_avg', sa.Float(), nullable=True, comment='平均质量得分'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True, comment='是否启用'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_skill_name', 'skills', ['name'], unique=False)
    op.create_index('idx_skill_trigger', 'skills', ['trigger_conditions'], unique=False, postgresql_using='gin')
    op.create_table('subjects',
    sa.Column('code', sa.String(length=20), nullable=False, comment='学科编码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='学科名称'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标路径'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序权重'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱（登录凭证）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='出生日期，用于计算年龄分级'),
    sa.Column('age_group', sa.String(length=10), nullable=False, comment='当前年龄分级编码'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像 URL'),
    sa.Column('total_score', sa.Integer(), server_default='0', nullable=True, comment='总积分'),
    sa.Column('streak_days', sa.Integer(), server_default='0', nullable=True, comment='连续学习天数'),
    sa.Column('current_correct_streak', sa.Integer(), server_default='0', nullable=False, comment='当前连续答对题数'),
    sa.Column('max_correct_streak', sa.Integer(), server_default='0', nullable=False, comment='最高连续答对题数'),
    sa.Column('total_answered', sa.Integer(), server_default='0', nullable=False, comment='累计作答数'),
    sa.Column('correct_answered', sa.Integer(), server_default='0', nullable=False, comment='累计答对数'),
    sa.Column('last_active_date', sa.Date(), nullable=True, comment='最后学习日期'),
    sa.Column('study_days_count', sa.Integer(), server_default='0', nullable=False, comment='累计学习天数'),
    sa.Column('behavior_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户行为模型（能力估计、行为模式、偏好冲突、置信度）'),
    sa.Column('last_login_date', sa.Date(), nullable=True, comment='上次登录日期'),
    sa.Column('admin_user_id', sa.Integer(), nullable=True, comment='管理后台用户 ID，用于关联外部管理系统'),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为管理员'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_age_group', 'users', ['age_group'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_table('daily_challenge_attempts',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['daily_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_daily_challenge_user_attempt')
    )
    op.create_index('idx_daily_challenge_attempt_score', 'daily_challenge_attempts', ['challenge_id', 'score'], unique=False)
    op.create_table('harness_runs',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('run_type', sa.String(length=50), nullable=False, comment='执行类型: question_generation / variant_generation / ai_explain'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: running / succeeded / failed'),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='输入参数'),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输出摘要'),
    sa.Column('model_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Token、模型、耗时等使用信息'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_harness_started', 'harness_runs', ['started_at'], unique=False)
    op.create_index('idx_harness_type', 'harness_runs', ['run_type'], unique=False)
    op.create_index('idx_harness_user', 'harness_runs', ['user_id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介'),
    sa.Column('subject_code', sa.String(length=20), nullable=False, comment='所属学科'),
    sa.Column('age_group_code', sa.String(length=10), nullable=False, comment='适用年龄段'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='难度: DIFF_EASY / DIFF_MEDIUM / DIFF_HARD'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='类型: TYPE_READ / TYPE_QUIZ / TYPE_GAME'),
    sa.Column('content_body', sa.Text(), nullable=False, comment='知识内容主体（Markdown）'),
    sa.Column('estimated_minutes', sa.Integer(), server_default='5', nullable=True, comment='预计完成时长（分钟）'),
    sa.Column('prerequisites', postgresql.ARRAY(sa.UUID()), nullable=True, comment='前置知识点 ID 列表'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True, comment='是否启用'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['age_group_code'], ['age_groups.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_age', 'knowledge_nodes', ['age_group_code'], unique=False)
    op.create_index('idx_node_diff', 'knowledge_nodes', ['difficulty_level'], unique=False)
    op.create_index('idx_node_subject', 'knowledge_nodes', ['subject_code'], unique=False)
    op.create_index('idx_node_type', 'knowledge_nodes', ['content_type'], unique=False)
    op.create_table('session_memories',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('memory_type', sa.String(length=50), nullable=False, comment='记忆类型: error_pattern / preference / quality_insight / behavior_pattern'),
    sa.Column('content', sa.Text(), nullable=False, comment='结构化记忆内容'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 (0-1)'),
    sa.Column('ttl_days', sa.Integer(), server_default='90', nullable=True, comment='生存天数'),
    sa.Column('related_topic', sa.String(length=200), nullable=True, comment='关联主题'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('is_expired', sa.Boolean(), server_default='false', nullable=True, comment='是否已过期'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_expires', 'session_memories', ['expires_at'], unique=False)
    op.create_index('idx_memory_topic', 'session_memories', ['related_topic'], unique=False)
    op.create_index('idx_memory_user', 'session_memories', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('achievement_id', sa.UUID(), nullable=False, comment='成就 ID'),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False, comment='达成时间'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_achievement_achieved', 'user_achievements', ['achievement_id'], unique=False)
    op.create_index('idx_user_achievement_user', 'user_achievements', ['user_id'], unique=False)
    op.create_index('uq_user_achievement_user_achievement', 'user_achievements', ['user_id', 'achievement_id'], unique=True)
    op.create_table('user_courses',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程ID'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='学习进度(0-100)'),
    sa.Column('completed_lessons', sa.Integer(), nullable=False, comment='已完成课时数'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: enrolled/completed'),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True, comment='最近学习时间'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course')
    )
    op.create_index(op.f('ix_user_courses_course_id'), 'user_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_courses_user_id'), 'user_courses', ['user_id'], unique=False)
    op.create_index('ix_user_courses_user_status', 'user_courses', ['user_id', 'status'], unique=False)
    op.create_table('error_logs',
    sa.Column('harness_run_id', sa.UUID(), nullable=True, comment='关联的 Harness 执行'),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='出错 Agent 名称'),
    sa.Column('step_name', sa.String(length=50), nullable=False, comment='步骤名称'),
    sa.Column('error_type', sa.String(length=50), nullable=False, comment='错误类型: SAFE_AUDIT / QUALITY_FAIL / PERF_DEGRADE / LOGIC_ERROR'),
    sa.Column('error_code', sa.String(length=10), nullable=False, comment='错误编码 (E001-E399)'),
    sa.Column('severity', sa.String(length=10), nullable=False, comment='严重度: P0 / P1 / P2'),
    sa.Column('raw_error', sa.Text(), nullable=False, comment='原始错误信息'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='错误上下文'),
    sa.Column('affected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='受影响的输出'),
    sa.Column('routing_target', sa.String(length=100), nullable=True, comment='路由目标 Agent'),
    sa.Column('auto_fix_attempted', sa.Boolean(), server_default='false', nullable=True, comment='是否尝试自动修复'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['harness_run_id'], ['harness_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_agent', 'error_logs', ['agent_name'], unique=False)
    op.create_index('idx_error_created', 'error_logs', ['created_at'], unique=False)
    op.create_index('idx_error_severity', 'error_logs', ['severity'], unique=False)
    op.create_index('idx_error_type', 'error_logs', ['error_type'], unique=False)
    op.create_table('generated_question_batches',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='发起生成的用户'),
    sa.Column('age_group_code', sa.String(length=10), nullable=False, comment='生成时使用的年龄分级'),
    sa.Column('subject_code', sa.String(length=20), nullable=False, comment='学科'),
    sa.Column('course_topic', sa.String(length=200), nullable=False, comment='课程主题'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='难度'),
    sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='题型列表'),
    sa.Column('question_count', sa.Integer(), nullable=False, comment='请求生成数量'),
    sa.Column('learning_goal', sa.String(length=200), nullable=True, comment='学习目标'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True, comment='状态: pending / passed / failed / partial'),
    sa.Column('prompt_version', sa.String(length=50), nullable=False, comment='Prompt 模板版本'),
    sa.Column('harness_run_id', sa.UUID(), nullable=True, comment='对应 Harness 执行记录'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['harness_run_id'], ['harness_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gqb_created', 'generated_question_batches', ['created_at'], unique=False)
    op.create_index('idx_gqb_topic', 'generated_question_batches', ['subject_code', 'course_topic'], unique=False)
    op.create_index('idx_gqb_user', 'generated_question_batches', ['user_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=False, comment='知识点 ID'),
    sa.Column('difficulty_level', sa.String(length=10), nullable=False, comment='学习时的难度'),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=True, comment='状态: in_progress / completed / abandoned'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=True, comment='正确数'),
    sa.Column('total_questions', sa.Integer(), server_default='0', nullable=True, comment='总题数'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_node', 'learning_sessions', ['knowledge_node_id'], unique=False)
    op.create_index('idx_session_user', 'learning_sessions', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('course_id', sa.UUID(), nullable=False, comment='所属课程ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='课时标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='课时描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='类型: video/text/interactive/quiz/game'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='课时时长(分钟)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='课时顺序'),
    sa.Column('content', sa.Text(), nullable=True, comment='课时内容'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=True, comment='关联知识点ID（quiz 类型课时绑定）'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index('ix_lessons_course_order', 'lessons', ['course_id', 'order'], unique=False)
    op.create_index('idx_lesson_knowledge_node', 'lessons', ['knowledge_node_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False, comment='题目 ID'),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=False, comment='所属知识点'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='难度'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题型: CHOICE / MULTIPLE_CHOICE / FILL_BLANK'),
    sa.Column('question_body', sa.Text(), nullable=False, comment='题目内容（Markdown）'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='选择题选项: [{key, value}]'),
    sa.Column('correct_answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='解析'),
    sa.Column('standard_time_seconds', sa.Integer(), server_default='30', nullable=True, comment='标准答题用时（秒）'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_diff', 'questions', ['difficulty_level'], unique=False)
    op.create_index('idx_question_node', 'questions', ['knowledge_node_id'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('harness_run_id', sa.UUID(), nullable=False, comment='所属 Harness Run'),
    sa.Column('step_name', sa.String(length=50), nullable=False, comment='步骤名称: intent / plan / memory / generate / quality / save'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='输入摘要'),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='输出摘要'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: succeeded / failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('error_type', sa.String(length=50), nullable=True, comment='错误类型: SAFE_AUDIT / QUALITY_FAIL / PERF_DEGRADE / LOGIC_ERROR'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['harness_run_id'], ['harness_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_name', 'tool_call_logs', ['tool_name'], unique=False)
    op.create_index('idx_tool_run', 'tool_call_logs', ['harness_run_id'], unique=False)
    op.create_index('idx_tool_status', 'tool_call_logs', ['status'], unique=False)
    op.create_table('answers',
    sa.Column('session_id', sa.UUID(), nullable=False, comment='会话 ID'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='题目 ID'),
    sa.Column('user_answer', sa.String(length=500), nullable=False, comment='用户答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否正确'),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False, comment='用时（秒）'),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='答题时间'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_question', 'answers', ['question_id'], unique=False)
    op.create_index('idx_answer_session', 'answers', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='用户ID'),
    sa.Column('course_id', sa.UUID(), nullable=True, comment='课程ID'),
    sa.Column('lesson_id', sa.UUID(), nullable=True, comment='课时ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('context', sa.JSON(), nullable=True, comment='上下文信息'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_course_id'), 'chat_messages', ['course_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_lesson_id'), 'chat_messages', ['lesson_id'], unique=False)
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('daily_challenge_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_answer', sa.String(length=500), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['daily_challenge_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_daily_challenge_answer'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('daily_challenge_questions',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['daily_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'position', name='uq_daily_challenge_position'),
    sa.UniqueConstraint('challenge_id', 'question_id', name='uq_daily_challenge_question')
    )
    op.create_table('generated_questions',
    sa.Column('batch_id', sa.UUID(), nullable=False, comment='生成批次 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=True, comment='可选关联知识点'),
    sa.Column('subject_code', sa.String(length=20), nullable=False, comment='学科'),
    sa.Column('course_topic', sa.String(length=200), nullable=False, comment='课程主题'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='难度'),
    sa.Column('question_type', sa.String(length=20), nullable=False, comment='题型'),
    sa.Column('question_body', sa.Text(), nullable=False, comment='题干'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='选项'),
    sa.Column('correct_answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('explanation', sa.Text(), nullable=False, comment='解析'),
    sa.Column('knowledge_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='知识点标签'),
    sa.Column('source_prompt', sa.Text(), nullable=False, comment='生成 Prompt 或 Prompt 摘要'),
    sa.Column('similarity_hash', sa.String(length=128), nullable=True, comment='去重用指纹'),
    sa.Column('quality_status', sa.String(length=20), server_default='unchecked', nullable=True, comment='质量状态: unchecked / passed / failed'),
    sa.Column('parent_question_id', sa.UUID(), nullable=True, comment='变式题来源'),
    sa.Column('language', sa.String(length=10), server_default='zh-CN', nullable=True, comment='题目语言'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['generated_question_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_question_id'], ['generated_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gq_created', 'generated_questions', ['created_at'], unique=False)
    op.create_index('idx_gq_diff', 'generated_questions', ['difficulty_level'], unique=False)
    op.create_index('idx_gq_language', 'generated_questions', ['language'], unique=False)
    op.create_index('idx_gq_type', 'generated_questions', ['question_type'], unique=False)
    op.create_index('idx_gq_user_topic', 'generated_questions', ['user_id', 'subject_code', 'course_topic'], unique=False)
    op.create_table('user_lessons',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('lesson_id', sa.UUID(), nullable=False, comment='课时ID'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程ID'),
    sa.Column('completed', sa.Boolean(), nullable=False, comment='是否已完成'),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False, comment='学习用时(秒)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson')
    )
    op.create_index(op.f('ix_user_lessons_course_id'), 'user_lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_lessons_lesson_id'), 'user_lessons', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_lessons_user_id'), 'user_lessons', ['user_id'], unique=False)
    op.create_table('wrong_questions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_wrong_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_wrong_answer', sa.Text(), server_default='', nullable=False),
    sa.Column('is_mastered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_note', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_wrong_question_user_question')
    )
    op.create_index('idx_wrong_question_user_review', 'wrong_questions', ['user_id', 'is_mastered', 'last_wrong_at'], unique=False)
    op.create_index('idx_wrong_question_user_subject', 'wrong_questions', ['user_id', 'subject'], unique=False)
    op.create_table('gamification_events',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('base_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('correct_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_achievements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_index('idx_gamification_event_user', 'gamification_events', ['user_id'], unique=False)
    op.create_table('question_quality_checks',
    sa.Column('generated_question_id', sa.UUID(), nullable=False, comment='被检查题目'),
    sa.Column('check_type', sa.String(length=50), nullable=False, comment='检查类型: answer / age / difficulty / duplicate / safety'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: passed / failed / warning'),
    sa.Column('score', sa.Float(), nullable=True, comment='检查得分'),
    sa.Column('message', sa.Text(), nullable=True, comment='检查说明'),
    sa.Column('checker_version', sa.String(length=50), nullable=False, comment='检查器版本'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_question_id'], ['generated_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_question', 'question_quality_checks', ['generated_question_id'], unique=False)
    op.create_index('idx_quality_status', 'question_quality_checks', ['status'], unique=False)
    op.create_table('wrong_question_events',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_index('idx_wrong_question_event_user_question', 'wrong_question_events', ['user_id', 'question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wrong_question_event_user_question', table_name='wrong_question_events')
    op.drop_table('wrong_question_events')
    op.drop_index('idx_quality_status', table_name='question_quality_checks')
    op.drop_index('idx_quality_question', table_name='question_quality_checks')
    op.drop_table('question_quality_checks')
    op.drop_index('idx_gamification_event_user', table_name='gamification_events')
    op.drop_table('gamification_events')
    op.drop_index('idx_wrong_question_user_subject', table_name='wrong_questions')
    op.drop_index('idx_wrong_question_user_review', table_name='wrong_questions')
    op.drop_table('wrong_questions')
    op.drop_index(op.f('ix_user_lessons_user_id'), table_name='user_lessons')
    op.drop_index(op.f('ix_user_lessons_lesson_id'), table_name='user_lessons')
    op.drop_index(op.f('ix_user_lessons_course_id'), table_name='user_lessons')
    op.drop_table('user_lessons')
    op.drop_index('idx_gq_user_topic', table_name='generated_questions')
    op.drop_index('idx_gq_type', table_name='generated_questions')
    op.drop_index('idx_gq_language', table_name='generated_questions')
    op.drop_index('idx_gq_diff', table_name='generated_questions')
    op.drop_index('idx_gq_created', table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_table('daily_challenge_questions')
    op.drop_table('daily_challenge_answers')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_lesson_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_course_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_answer_session', table_name='answers')
    op.drop_index('idx_answer_question', table_name='answers')
    op.drop_table('answers')
    op.drop_index('idx_tool_status', table_name='tool_call_logs')
    op.drop_index('idx_tool_run', table_name='tool_call_logs')
    op.drop_index('idx_tool_name', table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index('idx_question_node', table_name='questions')
    op.drop_index('idx_question_diff', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_lesson_knowledge_node', table_name='lessons')
    op.drop_index('ix_lessons_course_order', table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('idx_session_user', table_name='learning_sessions')
    op.drop_index('idx_session_node', table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('idx_gqb_user', table_name='generated_question_batches')
    op.drop_index('idx_gqb_topic', table_name='generated_question_batches')
    op.drop_index('idx_gqb_created', table_name='generated_question_batches')
    op.drop_table('generated_question_batches')
    op.drop_index('idx_error_type', table_name='error_logs')
    op.drop_index('idx_error_severity', table_name='error_logs')
    op.drop_index('idx_error_created', table_name='error_logs')
    op.drop_index('idx_error_agent', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('ix_user_courses_user_status', table_name='user_courses')
    op.drop_index(op.f('ix_user_courses_user_id'), table_name='user_courses')
    op.drop_index(op.f('ix_user_courses_course_id'), table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_index('idx_user_achievement_user', table_name='user_achievements')
    op.drop_index('idx_user_achievement_achieved', table_name='user_achievements')
    op.drop_index('uq_user_achievement_user_achievement', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('idx_memory_user', table_name='session_memories')
    op.drop_index('idx_memory_topic', table_name='session_memories')
    op.drop_index('idx_memory_expires', table_name='session_memories')
    op.drop_table('session_memories')
    op.drop_index('idx_node_type', table_name='knowledge_nodes')
    op.drop_index('idx_node_subject', table_name='knowledge_nodes')
    op.drop_index('idx_node_diff', table_name='knowledge_nodes')
    op.drop_index('idx_node_age', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index('idx_harness_user', table_name='harness_runs')
    op.drop_index('idx_harness_type', table_name='harness_runs')
    op.drop_index('idx_harness_started', table_name='harness_runs')
    op.drop_table('harness_runs')
    op.drop_index('idx_daily_challenge_attempt_score', table_name='daily_challenge_attempts')
    op.drop_table('daily_challenge_attempts')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_age_group', table_name='users')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_index('idx_skill_trigger', table_name='skills', postgresql_using='gin')
    op.drop_index('idx_skill_name', table_name='skills')
    op.drop_table('skills')
    op.drop_index('idx_evo_type', table_name='evolution_records')
    op.drop_index('idx_evo_target', table_name='evolution_records')
    op.drop_index('idx_evo_created', table_name='evolution_records')
    op.drop_table('evolution_records')
    op.drop_index(op.f('ix_daily_challenges_challenge_date'), table_name='daily_challenges')
    op.drop_table('daily_challenges')
    op.drop_index('ix_courses_subject_difficulty', table_name='courses')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_difficulty'), table_name='courses')
    op.drop_index(op.f('ix_courses_age_group'), table_name='courses')
    op.drop_index('ix_courses_active', table_name='courses')
    op.drop_table('courses')
    op.drop_table('age_groups')
    op.drop_table('achievements')
    # ### end Alembic commands ###
