"""establish question bank baseline

Revision ID: catalog_0001_baseline
Revises:
Create Date: 2026-07-22 06:22:27.401893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'catalog_0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('age_group', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_range', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'age_group', 'name')
    )
    op.create_index('idx_kp_subject_age', 'knowledge_points', ['subject', 'age_group'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), server_default=sa.text("'ai_generated'"), nullable=True),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('knowledge_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('variant_group_id', sa.String(length=50), nullable=True),
    sa.Column('cognitive_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_difficulty', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'zh'"), nullable=True),
    sa.Column('generation_source', sa.String(length=30), server_default=sa.text("'ai_generated'"), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), server_default=sa.text("'approved'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('idx_questions_knowledge_fp', 'questions', ['knowledge_fingerprint'], unique=False, postgresql_using='gin')
    op.create_index('idx_questions_language', 'questions', ['language'], unique=False)
    op.create_index('idx_questions_quality', 'questions', ['quality_score'], unique=False)
    op.create_index('idx_questions_review', 'questions', ['review_status'], unique=False)
    op.create_index('idx_subject_age', 'questions', ['subject', 'age_group'], unique=False)
    op.create_index('idx_type', 'questions', ['type'], unique=False)
    op.create_table('question_knowledge',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    op.create_index('idx_qk_primary', 'question_knowledge', ['question_id'], unique=False, postgresql_where=sa.text('is_primary IS true'))
    op.create_table('question_stats',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('correct_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('correct_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_time_seconds', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('calibrated_difficulty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_stats')
    op.drop_index('idx_qk_primary', table_name='question_knowledge', postgresql_where=sa.text('is_primary IS true'))
    op.drop_table('question_knowledge')
    op.drop_index('idx_type', table_name='questions')
    op.drop_index('idx_subject_age', table_name='questions')
    op.drop_index('idx_questions_review', table_name='questions')
    op.drop_index('idx_questions_quality', table_name='questions')
    op.drop_index('idx_questions_language', table_name='questions')
    op.drop_index('idx_questions_knowledge_fp', table_name='questions', postgresql_using='gin')
    op.drop_index('idx_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_kp_subject_age', table_name='knowledge_points')
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
